class CategoricalNumDict : 
    def __init__(self) -> None:
        self.dictionaries = {
            "Kitchen" : {
                'not_installed': 0,
                'usa_uninstalled': 1,
                'semi_equipped': 2,
                'usa_semi_equipped': 3,
                'installed': 4,
                'usa_installed': 5,
                'hyper_equipped': 6,
                'usa_hyper_equipped': 7
            } ,
            "PEB" : {
                'G' : 0,
                'G/F' : 1,
                'G/C' : 2,
                'F': 3, 
                'F/D': 4, 
                'F/C': 5, 
                'F/E': 6, 
                'E': 7, 
                'E/D': 8, 
                'E/C': 9, 
                'D': 10, 
                'C': 11, 
                'B/A': 12, 
                'B': 13, 
                'A': 14, 
                'A+': 15, 
                'A++': 16
                }, 
            "FloodingZone" :  {
                'recognized_n_circumscribed_flood_zone': 0,
                'recognized_flood_zone': 1,
                'recognized_n_circumscribed_waterside_flood_zone': 2,
                'circumscribed_flood_zone': 3,
                'circumscribed_waterside_zone': 4,
                'possible_n_circumscribed_flood_zone': 5,
                'possible_flood_zone': 6,
                'possible_n_circumscribed_waterside_zone': 7,
                'non_flood_zone': 8
            },
            "Province" : {
                'west_flanders' :0,
                'hainaut' :1 ,
                'limburg' : 2,
                'brussels' : 3,
                'walloon_brabant' :4 ,
                'antwerp' : 5,
                'flemish_brabant' : 6,
                'east_flanders' :7 ,
                'namur' : 8,
                'liège' : 9,
                'luxembourg' : 10,
            }, 
            "Region"  : {
                'flanders' : 0 ,
                'wallonie' : 1 ,
                'brussels' : 2 ,
            },
            "StateOfBuilding" : {
                'to_be_done_up' : 0 ,
                'to_renovate' : 1 ,
                'to_restore' : 2 ,
                'good' : 3 ,
                'just_renovated' : 4 ,
                'as_new' :5,
            },
            "TypeOfSale" : {
                "residential_sale" : 0,
                "residential_monthly_rent" : 1,
            }, 
            "District" : {
                'aalst': 0,
                'antwerp': 1,
                'arlon': 2,
                'ath': 3,
                'bastogne': 4,
                'brugge': 5,
                'brussels': 6,
                'charleroi': 7,
                'dendermonde': 8,
                'diksmuide': 9,
                'dinant': 10,
                'eeklo': 11,
                'ghent': 12,
                'halle-vilvoorde': 13,
                'hasselt': 14,
                'houtain-le-val': 15,
                'kortrijk': 16,
                'leuven': 17,
                'liège': 18,
                'maaseik': 19,
                'mechelen': 20,
                'mons': 21,
                'naxhelet': 22,
                'ninove': 23,
                'nivelles': 24,
                'ostend': 25,
                'oudenaarde': 26,
                'pepinster': 27,
                'rachecourt': 28,
                'roeselare': 29,
                'seraing': 30,
                'soignies': 31,
                'stavelot': 32,
                'termonde': 33,
                'tielt': 34,
                'tienen': 35,
                'tongeren': 36,
                'turnhout': 37,
                'veurne': 38,
                'vielsalm': 39,
                'vilvoorde': 40,
                'waregem': 41,
                'ypres': 42
            }, 
            "SubtypeOfProperty" : {
                'apartment': 0,
                'apartment_block': 1,
                'bungalow': 2,
                'castle': 3,
                'chalet': 4,
                'country_cottage': 5,
                'duplex': 6,
                'exceptional_property': 7,
                'farmhouse': 8,
                'flat_studio': 9,
                'ground_floor': 10,
                'house': 11,
                'kot': 12,
                'loft': 13,
                'manor_house': 14,
                'mansion': 15,
                'mixed_use_building': 16,
                'other_property': 17,
                'pavilion': 18,
                'penthouse': 19,
                'service_flat': 20,
                'town_house': 21,
                'triplex': 22,
                'villa': 23
            }
        }
    
    def get_dict(self, key):
        return self.dictionaries.get(key)
        